import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: Platform.OS === "android" ? 40 : 15,
      paddingBottom: 15,
    },
    userInfo: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    avatarBorder: {
      width: 44,
      height: 44,
      borderRadius: 22,
      borderWidth: 2,
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
    },
    welcomeText: {
      fontSize: 16,
      fontWeight: "700",
    },
    subWelcomeText: {
      fontSize: 12,
      marginTop: 1,
    },
    notificationButton: {
      position: "relative",
      padding: 8,
    },
    notificationBadge: {
      position: "absolute",
      top: 6,
      right: 6,
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingBottom: 40,
    },
    statsGrid: {
      flexDirection: "row",
      gap: 16,
      marginTop: 10,
      marginBottom: 24,
    },
    statCard: {
      flex: 1,
      padding: 16,
      borderRadius: 16,
      borderWidth: 1,
      alignItems: "center",
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 5,
      elevation: 3,
    },
    statLabel: {
      fontSize: 12,
      fontWeight: "500",
      marginBottom: 6,
    },
    statNumberContainer: {
      flexDirection: "row",
      alignItems: "baseline",
      gap: 2,
    },
    statNumber: {
      fontSize: 28,
      fontWeight: "800",
    },
    statUnit: {
      fontSize: 12,
      fontWeight: "600",
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 14,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "700",
    },
    seeAllButton: {
      fontSize: 14,
      fontWeight: "600",
    },
    featuredCard: {
      borderWidth: 1,
      borderRadius: 20,
      padding: 20,
      position: "relative",
      marginBottom: 20,
      shadowColor: "#000",
      shadowOpacity: 0.2,
      shadowRadius: 10,
      elevation: 5,
    },
    badgeContainer: {
      position: "absolute",
      top: 0,
      right: 0,
      overflow: "hidden",
      borderTopRightRadius: 19,
      borderBottomLeftRadius: 12,
    },
    featuredBadge: {
      fontSize: 9,
      fontWeight: "800",
      paddingHorizontal: 12,
      paddingVertical: 6,
      letterSpacing: 0.8,
    },
    teamsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 15,
      marginBottom: 15,
    },
    teamContainer: {
      alignItems: "center",
      flex: 1,
    },
    flag: {
      width: 60,
      height: 40,
      borderRadius: 6,
    },
    teamName: {
      fontSize: 13,
      fontWeight: "800",
      marginTop: 8,
      textAlign: "center",
    },
    vsContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    scoreBox: {
      width: 32,
      height: 38,
      borderRadius: 6,
      justifyContent: "center",
      alignItems: "center",
    },
    scoreText: {
      fontSize: 16,
      fontWeight: "700",
    },
    vsText: {
      fontSize: 12,
      fontWeight: "700",
      fontStyle: "italic",
    },
    matchMeta: {
      alignItems: "center",
      gap: 4,
      marginBottom: 18,
    },
    metaRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    metaText: {
      fontSize: 12,
      fontWeight: "500",
    },
    groupText: {
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    palpiteButton: {
      height: 52,
      borderRadius: 14,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 8,
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 4,
    },
    palpiteButtonText: {
      fontWeight: "800",
      fontSize: 14,
      letterSpacing: 0.5,
    },
    listContainer: {
      gap: 12,
    },
    matchRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: 14,
      borderRadius: 16,
      borderWidth: 1,
    },
    rowTeam: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flex: 1,
    },
    alignRight: {
      justifyContent: "flex-end",
    },
    smallFlag: {
      width: 30,
      height: 20,
      borderRadius: 3,
    },
    rowTeamText: {
      fontSize: 13,
      fontWeight: "600",
    },
    rowInfo: {
      alignItems: "center",
      paddingHorizontal: 8,
    },
    rowDate: {
      fontSize: 11,
      fontWeight: "700",
    },
    rowGroup: {
      fontSize: 9,
      marginTop: 1,
    },
    chevron: {
      marginLeft: 6,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.6)",
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    modalContent: {
      width: "100%",
      maxWidth: 440,
      borderRadius: 24,
      borderWidth: 1,
      padding: 24,
      maxHeight: "80%",
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: "800",
    },
    modalScroll: {
      maxHeight: 350,
      marginVertical: 10,
    },
    modalEmptyText: {
      textAlign: "center",
      fontSize: 14,
      marginVertical: 24,
    },
    notificationCard: {
      paddingVertical: 12,
      borderBottomWidth: 1,
      gap: 6,
    },
    notificationHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    notificationTitle: {
      fontSize: 14,
      fontWeight: "700",
    },
    notificationDate: {
      fontSize: 10,
      fontWeight: "500",
    },
    notificationMsg: {
      fontSize: 13,
      lineHeight: 18,
    },
    modalFooter: {
      flexDirection: "row",
      justifyContent: "flex-end",
      marginTop: 16,
    },
    modalButton: {
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
    },
    modalButtonText: {
      fontSize: 13,
      fontWeight: "700",
      color: "#FFF",
    },
  });