import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1 },
    centerContent: { flex: 1, justifyContent: "center", alignItems: "center" },
    header: {
      paddingHorizontal: 20,
      paddingTop: Platform.OS === "android" ? 40 : 15,
      paddingBottom: 15,
      alignItems: "center",
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    profileCard: {
      alignItems: "center",
      paddingVertical: 30,
      paddingHorizontal: 20,
    },
    avatarBorder: {
      width: 96,
      height: 96,
      borderRadius: 48,
      borderWidth: 3,
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
      marginBottom: 16,
    },
    avatar: { width: 88, height: 88, borderRadius: 44 },
    nameRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 4,
    },
    nameText: { fontSize: 18, fontWeight: "700" },
    emailText: { fontSize: 13 },
    statsRow: {
      flexDirection: "row",
      gap: 16,
      marginTop: 12,
    },
    statMini: { fontSize: 12, fontWeight: "700" },
    editRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      width: "100%",
      maxHeight: 46,
      paddingHorizontal: 20,
      marginBottom: 4,
    },
    input: {
      flex: 1,
      height: 40,
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 12,
      fontSize: 14,
    },
    saveBtn: {
      width: 40,
      height: 40,
      borderRadius: 8,
      justifyContent: "center",
      alignItems: "center",
    },
    cancelBtn: {
      width: 40,
      height: 40,
      borderRadius: 8,
      borderWidth: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    menuContainer: { paddingHorizontal: 20, gap: 12, marginTop: 10 },
    menuItem: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 16,
      borderRadius: 14,
      borderWidth: 1,
    },
    menuLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
    menuText: { fontSize: 14, fontWeight: "600" },
    confirmBox: {
      marginHorizontal: 20,
      marginTop: 16,
      padding: 16,
      borderRadius: 14,
      borderWidth: 1,
    },
    confirmTitle: {
      fontSize: 15,
      fontWeight: "700",
      marginBottom: 6,
    },
    confirmMessage: {
      fontSize: 13,
      marginBottom: 14,
    },
    confirmActions: {
      flexDirection: "row",
      gap: 10,
    },
    confirmBtn: {
      flex: 1,
      height: 44,
      borderRadius: 10,
      borderWidth: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    footerBanner: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 6,
      position: "absolute",
      bottom: 30,
      left: 20,
      right: 20,
    },
    footerText: { fontSize: 11, textAlign: "center" },
});